#pragma once

enum EComponentType : uint8
{
	ECT_SKILLTIMER,
	ECT_COLLISION,
	ECT_AIMOVEMENT,
	ECT_MAX,
};

enum EColliderType: uint8
{
	COLLIDER_BOX = Protocol::COLLISION_TYPE_BOX ,
	COLLIDER_CIRCLE = Protocol::COLLISION_TYPE_CIRCLE,
	COLLIDER_RAY = Protocol::COLLISION_TYPE_NONE,
};

enum EBossMontageType : uint8
{
	MONTAGE_TYPE_NONE = 0,
	MONTAGE_TYPE_START = 1,
	MONTAGE_TYPE_ING = 2,
	MONTAGE_TYPE_END = 3,
};

enum EBossSkillType : uint8
{
	EBST_NONE,
	EBST_DEFAULT,
	EBST_RUSH,
	EBST_MAX
};